### PR TITLE
HW3-with styling

### PR DESCRIPTION
**Pull request by alch-0**
Just style edits.
No code changes (code is already approved).

### CODE REVIEW

**Comment by alch-0** [comment]
Applied style changes to the code.

**Comment by alch-0** [comment]
> You should use StyleCop style

Yes that's what I used. 
I didn't put in file headers and descriptions for methods, classes, etc., because those things are optional.

**Comment by vsatkov** [comment]
> 
> 
> > You should use StyleCop style
> 
> Yes that's what I used.
> I didn't put in file headers and descriptions for methods, classes, etc., because those things are optional.

Please, send me a link with indicating that this it is optional.

**Comment by alch-0** [comment]
> You should use StyleCop style
> 
> Yes that's what I used.
> I didn't put in file headers and descriptions for methods, classes, etc., because those things are optional.
> 
> Please, send me a link with indicating that this it is optional.

We discussed it in class. There were no strict requirements regarding comments (even the actual working projects differ in their requirements to XML comments and headers, Denis mentioned that).

Also StyleCop is not a standard, it is just an application that checks whether the code confirms to a wide set of rules, even by default not all of those checks are on, and you can tune StyleCop so it matches your requirements.

**Pull request merged**
